<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Basu Pokharel',
                'email' => 'basu.pokharel@example.com',
                'address' => 'Oulu, Finland',
                // 'Total_Booked' => 10,
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 1,
                'hasKey' => 1,
                'contact_no' => 837458949,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'John Doe',
                'email' => 'john.doe@example.com',
                'address' => 'Helsinki, Finland',
                // 'Total_Booked' => 3,
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 0,
                'hasKey' => 1,
                'contact_no' => 837458949,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maria Virtanen',
                'email' => 'maria.virtanen@example.com',
                'address' => 'Espoo, Finland',
                // 'Total_Booked' => 7,
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 0,
                'hasKey' => 1,
                'contact_no' => 837458949,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alex Johnson',
                'email' => 'alex.johnson@example.com',
                'address' => 'Vantaa, Finland',
                // 'Total_Booked' => 1,
                'email_verified_at' => null,
                'password' => bcrypt('password123'),
                'isAdmin' => 0,
                'hasKey' => 1,
                'contact_no' => 837458949,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sara Laine',
                'email' => 'sara.laine@example.com',
                'address' => 'Tampere, Finland',
                // 'Total_Booked' => 5,
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 0,
                'hasKey' => 1,
                'contact_no' => 837458949,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Alex Chen',
                'email' => 'alex.chen@example.com',
                'address' => 'Helsinki, Finland',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 0,
                'hasKey' => 1,
                'contact_no' => 445678901,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maria Garcia',
                'email' => 'maria.garcia@example.com',
                'address' => 'Espoo, Finland',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 1,
                'hasKey' => 1,
                'contact_no' => 501234567,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'James Wilson',
                'email' => 'james.wilson@example.com',
                'address' => 'Vantaa, Finland',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 0,
                'hasKey' => 0,
                'contact_no' => 612345678,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lisa Johnson',
                'email' => 'lisa.johnson@example.com',
                'address' => 'Turku, Finland',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 0,
                'hasKey' => 1,
                'contact_no' => 723456789,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'David Brown',
                'email' => 'david.brown@example.com',
                'address' => 'Oulu, Finland',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 1,
                'hasKey' => 1,
                'contact_no' => 834567890,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Emma Davis',
                'email' => 'emma.davis@example.com',
                'address' => 'Jyväskylä, Finland',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 0,
                'hasKey' => 0,
                'contact_no' => 945678901,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Robert Miller',
                'email' => 'robert.miller@example.com',
                'address' => 'Lahti, Finland',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 0,
                'hasKey' => 1,
                'contact_no' => 556789012,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sophia Taylor',
                'email' => 'sophia.taylor@example.com',
                'address' => 'Kuopio, Finland',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 1,
                'hasKey' => 1,
                'contact_no' => 667890123,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thomas Anderson',
                'email' => 'thomas.anderson@example.com',
                'address' => 'Pori, Finland',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 0,
                'hasKey' => 0,
                'contact_no' => 778901234,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Olivia Martinez',
                'email' => 'olivia.martinez@example.com',
                'address' => 'Kotka, Finland',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'isAdmin' => 0,
                'hasKey' => 1,
                'contact_no' => 889012345,
                'remember_token' => Str::random(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ];
        User::insert($users);
    }
}
